// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Method               string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Headers              []*Request_Header `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Content              string            `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_http_cf0fa05f1901d355, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetHeaders() []*Request_Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Request) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Request_Header struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Header) Reset()         { *m = Request_Header{} }
func (m *Request_Header) String() string { return proto.CompactTextString(m) }
func (*Request_Header) ProtoMessage()    {}
func (*Request_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_http_cf0fa05f1901d355, []int{0, 0}
}
func (m *Request_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Header.Unmarshal(m, b)
}
func (m *Request_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Header.Marshal(b, m, deterministic)
}
func (dst *Request_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Header.Merge(dst, src)
}
func (m *Request_Header) XXX_Size() int {
	return xxx_messageInfo_Request_Header.Size(m)
}
func (m *Request_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Header proto.InternalMessageInfo

func (m *Request_Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Request_Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "main.Request")
	proto.RegisterType((*Request_Header)(nil), "main.Request.Header")
}

func init() { proto.RegisterFile("http.proto", fileDescriptor_http_cf0fa05f1901d355) }

var fileDescriptor_http_cf0fa05f1901d355 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x28, 0x29, 0x29,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x9a, 0xcb, 0xc8,
	0xc5, 0x1e, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc6, 0xc5, 0x96, 0x9b, 0x5a, 0x92,
	0x91, 0x9f, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe5, 0x09, 0xe9, 0x71, 0xb1, 0x67,
	0xa4, 0x26, 0xa6, 0xa4, 0x16, 0x15, 0x4b, 0x30, 0x2b, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xe8, 0x81,
	0xf4, 0xea, 0x41, 0xf5, 0xe9, 0x79, 0x80, 0x25, 0x83, 0x60, 0x8a, 0x84, 0x24, 0xb8, 0xd8, 0x93,
	0xf3, 0xf3, 0x4a, 0x52, 0xf3, 0x4a, 0x24, 0x58, 0xc0, 0x06, 0xc1, 0xb8, 0x52, 0x06, 0x5c, 0x6c,
	0x10, 0xc5, 0x42, 0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x50, 0x8b, 0x40, 0x4c, 0x21, 0x11, 0x2e,
	0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26, 0xb0, 0x18, 0x84, 0x93, 0xc4, 0x06, 0x76, 0xac,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xda, 0x12, 0xb9, 0x17, 0xba, 0x00, 0x00, 0x00,
}
